//! CMakeLists.txt generator using Tera templates.
//!
//! Generates a root `CMakeLists.txt` and one per module.  Templates are
//! hard-coded as strings so the binary is self-contained.
//!
//! ## Output strategy
//!
//! | Scenario | Behaviour |
//! |---|---|
//! | Target file does not exist | Write directly. |
//! | Target file exists, content differs, `force=true` | Overwrite directly (init). |
//! | Target file exists, content differs, `force=false` | Write `CMakeLists.txt.new` and print a diff hint (sync). |
//! | Target file contains `# USER_START` … `# USER_END` blocks | Preserve those blocks in the output. |

use crate::models::dependency::{DependencyGraph, DependencyType};
use crate::models::error::{FbGenError, FbGenResult};
use crate::models::module::{CMakeModule, TargetType};
use crate::models::project::{ProjectConfig, TargetArch, ToolchainConfig};
use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use tera::{Context, Tera};

// ── Hard-coded Tera templates ──────────────────────────────────────────────

/// Root `CMakeLists.txt` template.
const ROOT_TEMPLATE: &str = r#"# Generated by fb-gen — do not edit manually.
# Run `fb-gen run` to regenerate.
cmake_minimum_required(VERSION {{ cmake_min_version }})
project({{ project_name }} VERSION {{ version }} LANGUAGES {{ languages }})

# ── Global include directories ──────────────────────────────────────────────
{% for d in global_include_dirs -%}
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/{{ d }})
{% endfor %}

{% if has_cpp -%}
# ── C++ standard ────────────────────────────────────────────────────────────
set(CMAKE_CXX_STANDARD {{ cpp_standard }})
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

{% endif -%}
{% if c_standard -%}
set(CMAKE_C_STANDARD {{ c_standard }})
set(CMAKE_C_STANDARD_REQUIRED ON)
{% endif %}

# ── Sub-modules ─────────────────────────────────────────────────────────────
{% for module in subdirs -%}
add_subdirectory({{ module }})
{% endfor %}

# ── User customisations ─────────────────────────────────────────────────────
# USER_START
{% for um in user_modules -%}
add_subdirectory({{ um }})
{% endfor %}
# USER_END
"#;

/// Per-module `CMakeLists.txt` template.
///
/// `target_name` is the CMake target identifier:
/// - For executable modules it equals the project name so that
///   `${CMAKE_PROJECT_NAME}` references in user-provided CMake files
///   (e.g. STM32CubeMX) resolve correctly.
/// - For all other modules it equals the sanitised directory name.
const MODULE_TEMPLATE: &str = r#"# Generated by fb-gen — do not edit manually.
# Module: {{ module_name }}

{% if is_executable -%}
# ── Executable ──────────────────────────────────────────────────────────────
add_executable({{ target_name }}
{%- for src in sources %}
    {{ src }}
{%- endfor %}
)
{% elif is_header_only -%}
# ── Header-only library ─────────────────────────────────────────────────────
add_library({{ target_name }} INTERFACE)
target_include_directories({{ target_name }} INTERFACE
{%- for d in include_dirs %}
    ${CMAKE_CURRENT_SOURCE_DIR}/{{ d }}
{%- endfor %}
)
{% else -%}
# ── Static library ──────────────────────────────────────────────────────────
add_library({{ target_name }} STATIC
{%- for src in sources %}
    {{ src }}
{%- endfor %}
{%- for hdr in headers %}
    {{ hdr }}
{%- endfor %}
)
{% endif %}

{% if asm_sources and asm_sources|length > 0 -%}
set({{ name_upper }}_ASM_SOURCES
{%- for src in asm_sources %}
    {{ src }}
{%- endfor %}
)
target_sources({{ target_name }} PRIVATE ${ {{- name_upper -}}_ASM_SOURCES})
{% endif %}

{% if include_dirs and not is_header_only -%}
# ── Include directories ─────────────────────────────────────────────────────
target_include_directories({{ target_name }} PUBLIC
{%- for d in include_dirs %}
    ${CMAKE_CURRENT_SOURCE_DIR}/{{ d }}
{%- endfor %}
)
{% endif %}

{% if dependencies -%}
# ── Dependencies ────────────────────────────────────────────────────────────
{% for dep in dependencies -%}
target_link_libraries({{ target_name }}{% if is_header_only %} INTERFACE{% endif %} {{ dep.name }})
{% endfor %}
{% endif %}

{% if compile_features -%}
# ── Compile features ───────────────────────────────────────────────────────
target_compile_features({{ target_name }} PUBLIC
{%- for f in compile_features %}
    {{ f }}
{%- endfor %}
)
{% endif %}

{% if compile_definitions -%}
# ── Compile definitions ─────────────────────────────────────────────────────
target_compile_definitions({{ target_name }} PRIVATE
{%- for d in compile_definitions %}
    {{ d }}
{%- endfor %}
)
{% endif %}

{% if linker_scripts and linker_scripts|length > 0 -%}
# ── Linker script ───────────────────────────────────────────────────────────
{% for ld in linker_scripts -%}
target_link_options({{ target_name }} PRIVATE -T "${CMAKE_CURRENT_SOURCE_DIR}/{{ ld }}")
{% endfor %}
{% endif %}

# ── User customisations ─────────────────────────────────────────────────────
# USER_START
# USER_END
"#;

/// `cmake/toolchain.cmake` template for embedded cross-compilation.
const TOOLCHAIN_TEMPLATE: &str = r#"# Auto-generated toolchain file by fb-gen

set(CMAKE_SYSTEM_NAME               {{ system_name }})
set(CMAKE_SYSTEM_PROCESSOR          {{ processor }})

set(CMAKE_C_COMPILER_ID GNU)
set(CMAKE_CXX_COMPILER_ID GNU)

# Some default GCC settings
# {{ prefix }} must be part of path environment
set(TOOLCHAIN_PREFIX                {{ prefix }})

set(CMAKE_C_COMPILER                ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER              ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER              ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_LINKER                    ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_OBJCOPY                   ${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_SIZE                      ${TOOLCHAIN_PREFIX}size)

set(CMAKE_EXECUTABLE_SUFFIX_ASM     ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C       ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_CXX     ".elf")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# ── Sysroot (auto-detected) ──────────────────────────────────
{% if sysroot -%}
set(CMAKE_SYSROOT {{ sysroot }})
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT}{% for p in find_root_path %} {{ p }}{% endfor %})
{% endif -%}

# ── Cross-compilation root paths ─────────────────────────────
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# MCU specific flags
set(TARGET_FLAGS "{{ target_flags }} ")

set(CMAKE_C_FLAGS "${TARGET_FLAGS}")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -fdata-sections -ffunction-sections -fstack-usage")
set(CMAKE_ASM_FLAGS "${CMAKE_C_FLAGS} -x assembler-with-cpp -MMD -MP")

set(CMAKE_C_FLAGS_DEBUG "-O0 -g3")
set(CMAKE_C_FLAGS_RELEASE "-Os -g0")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g3")
set(CMAKE_CXX_FLAGS_RELEASE "-Os -g0")

set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -fno-rtti -fno-exceptions -fno-threadsafe-statics")

set(CMAKE_EXE_LINKER_FLAGS "${TARGET_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}{{ ld_flag }}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --specs=nano.specs")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-Map=${CMAKE_PROJECT_NAME}.map -Wl,--gc-sections")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--print-memory-usage")
set(TOOLCHAIN_LINK_LIBRARIES "m")

# ── User customisations ──────────────────────────────────────────
# USER_START
# USER_END
"#;

// ── Generator ──────────────────────────────────────────────────────────────

/// Generates CMakeLists.txt files from modules and dependency information.
pub struct CMakeGenerator {
    config: ProjectConfig,
    tera: Tera,
}

impl CMakeGenerator {
    /// Create a new generator tied to the given project configuration.
    pub fn new(config: &ProjectConfig) -> FbGenResult<Self> {
        let mut tera = Tera::default();

        // Register hard-coded templates.
        tera.add_raw_template("root", ROOT_TEMPLATE)
            .map_err(FbGenError::Template)?;
        tera.add_raw_template("module", MODULE_TEMPLATE)
            .map_err(FbGenError::Template)?;
        tera.add_raw_template("toolchain", TOOLCHAIN_TEMPLATE)
            .map_err(FbGenError::Template)?;

        Ok(Self {
            config: config.clone(),
            tera,
        })
    }

    /// Generate all CMakeLists.txt files.
    ///
    /// * Writes the root `CMakeLists.txt` to `config.root`.
    /// * Writes one `CMakeLists.txt` per module into its directory.
    /// * `force=true` (init): overwrite existing files directly.
    /// * `force=false` (sync): if a target file already exists and differs from
    ///   the generated content, the new content is written to
    ///   `CMakeLists.txt.new` and a warning is printed.
    /// * `# USER_START` … `# USER_END` blocks from existing files are
    ///   preserved in the generated output.
    pub fn generate(
        &self,
        modules: &[CMakeModule],
        graph: &DependencyGraph,
        force: bool,
        user_modules: &[PathBuf],
    ) -> FbGenResult<()> {
        let root_ld_scripts = detect_linker_scripts(&self.config.root);

        // ── Root CMakeLists.txt ────────────────────────────────────────
        let root_content = self.render_root(modules, graph, user_modules)?;
        let root_path = self.config.root.join("CMakeLists.txt");
        self.write_if_changed(&root_path, &root_content, "root", force)?;

        // ── Toolchain file (cross-compile only) ───────────────────────
        // Only generate a toolchain file when the user does NOT already have
        // one (e.g. from STM32CubeMX, CMakePresets, or manual setup).
        // Never overwrite a user-provided toolchain file.
        if !self.user_has_toolchain_file() {
            if let Some(toolchain_content) = self.render_toolchain(&root_ld_scripts)? {
                let toolchain_path = self.config.root.join("cmake").join("toolchain.cmake");
                // Ensure parent directory exists.
                if let Some(parent) = toolchain_path.parent() {
                    fs::create_dir_all(parent).map_err(FbGenError::Io)?;
                }
                self.write_if_changed(
                    &toolchain_path,
                    &toolchain_content,
                    "toolchain.cmake",
                    force,
                )?;
            }
        }

        // ── Per-module CMakeLists.txt ──────────────────────────────────
        for module in modules {
            // Skip root — we already handled it.
            if module.is_root {
                continue;
            }

            let mut deps: Vec<(String, DependencyType)> = graph.get_dependencies(&module.name);

            // Augment with companion source modules for header-only
            // dependencies.  When A depends on a header-only B, it also
            // needs to link against B's sibling source module (e.g.
            // Drivers_..._Inc → Drivers_..._Src) so that the function
            // implementations are available at link time.
            Self::augment_companion_sources(&mut deps, &module.name, modules, graph);

            let content = self.render_module(module, &deps, graph)?;
            let module_cmake_path = module.path.join("CMakeLists.txt");
            self.write_if_changed(&module_cmake_path, &content, &module.name, force)?;
        }

        Ok(())
    }

    /// Force-generate `cmake/toolchain.cmake` even when a user-owned toolchain
    /// file is detected.  Used when `device_defines` have been configured and
    /// the preset must be switched to fb-gen's own toolchain file.
    pub fn force_generate_toolchain(&self) -> FbGenResult<()> {
        let root_ld_scripts = detect_linker_scripts(&self.config.root);
        if let Some(content) = self.render_toolchain(&root_ld_scripts)? {
            let path = self.config.root.join("cmake").join("toolchain.cmake");
            self.write_if_changed(&path, &content, "toolchain.cmake", true)?;
        }
        Ok(())
    }

    // ── Private helpers ─────────────────────────────────────────────────────

    /// Render the root CMakeLists.txt.
    fn render_root(&self, modules: &[CMakeModule], graph: &DependencyGraph, user_modules: &[PathBuf]) -> FbGenResult<String> {
        let mut ctx = Context::new();

        ctx.insert("cmake_min_version", &self.config.cmake_min_version);
        ctx.insert("project_name", &self.config.name);
        ctx.insert("version", &self.config.version);

        // Determine if any module has C++ source files (and project isn't pure C).
        let has_cpp = modules.iter().any(|m| {
            m.sources
                .iter()
                .any(|s| matches!(s.source_type, crate::models::module::SourceType::CppSource))
        }) && self.config.language != "C";

        // Determine languages: add ASM and/or CXX based on actual sources present.
        let has_asm = modules.iter().any(|m| !m.asm_sources.is_empty());
        let languages = match (has_cpp, has_asm) {
            (true, true) => "C CXX ASM",
            (true, false) => "C CXX",
            (false, true) => "C ASM",
            (false, false) => "C",
        };
        ctx.insert("languages", languages);
        ctx.insert("has_cpp", &has_cpp);
        ctx.insert("cpp_standard", &self.config.cpp_standard);

        // C standard: always set if non-empty.
        let c_standard = if self.config.c_standard.is_empty() {
            String::new()
        } else {
            self.config.c_standard.clone()
        };
        ctx.insert("c_standard", &c_standard);

        // Collect global include directories: unique dirs across all modules.
        let global_include_dirs: Vec<String> = {
            let mut dirs: HashSet<String> = HashSet::new();
            for m in modules {
                for d in &m.include_dirs {
                    dirs.insert(d.to_string_lossy().to_string());
                }
            }
            let mut sorted: Vec<_> = dirs.into_iter().collect();
            sorted.sort();
            sorted
        };
        ctx.insert("global_include_dirs", &global_include_dirs);

        // Subdirectories to add (non-root modules), topologically sorted
        // so dependencies are declared before the modules that depend on them.
        let ordered_names = graph.topological_order().unwrap_or_else(|_| {
            modules
                .iter()
                .filter(|m| !m.is_root)
                .map(|m| m.name.clone())
                .collect()
        });

        let subdirs: Vec<String> = ordered_names
            .iter()
            .filter_map(|name| {
                modules
                    .iter()
                    .find(|m| &m.name == name && !m.is_root)
                    .map(|m| m.relative_path.to_string_lossy().to_string())
            })
            .collect();
        let user_module_dirs: Vec<String> = user_modules
            .iter()
            .map(|p| p.to_string_lossy().to_string())
            .collect();
        ctx.insert("user_modules", &user_module_dirs);

        ctx.insert("subdirs", &subdirs);

        self.tera.render("root", &ctx).map_err(FbGenError::Template)
    }

    /// Render a per-module CMakeLists.txt.
    fn render_module(
        &self,
        module: &CMakeModule,
        deps: &[(String, DependencyType)],
        graph: &DependencyGraph,
    ) -> FbGenResult<String> {
        // Defence-in-depth: root module with empty name should never reach here
        // (generate() skips is_root modules), but guard against it anyway.
        if module.name.is_empty() && module.is_root {
            return Err(FbGenError::GenerationFailed(
                "Cannot render per-module CMakeLists.txt for root module".into(),
            ));
        }

        let mut ctx = Context::new();

        ctx.insert("module_name", &module.name);

        let is_executable = module.target_type == crate::models::module::TargetType::Executable;
        let is_header_only = module.target_type == crate::models::module::TargetType::HeaderOnly;
        ctx.insert("is_executable", &is_executable);
        ctx.insert("is_header_only", &is_header_only);

        // Executable targets use the project name so that user-provided
        // CMake files (e.g. STM32CubeMX) can reference the executable via
        // ${CMAKE_PROJECT_NAME}. Libraries keep their directory-based name.
        let target_name: String = if is_executable {
            self.config.name.clone()
        } else {
            module.name.clone()
        };
        ctx.insert("target_name", &target_name);

        // Uppercase name for ASM_SOURCES variable.
        let name_upper = module.name.to_uppercase();
        ctx.insert("name_upper", &name_upper);

        // Source file paths relative to the module directory.
        // When a file lives outside the module dir (e.g. merged from the
        // project root), a "../" relative path is computed so CMake can
        // find it.
        let sources: Vec<String> = module
            .sources
            .iter()
            .map(|s| {
                Self::relative_to_module(&module.path, &s.path)
                    .to_string_lossy()
                    .to_string()
            })
            .collect();
        ctx.insert("sources", &sources);

        // Headers (only for static library targets).
        let headers: Vec<String> = module
            .headers
            .iter()
            .map(|h| {
                Self::relative_to_module(&module.path, &h.path)
                    .to_string_lossy()
                    .to_string()
            })
            .collect();
        ctx.insert("headers", &headers);

        // Assembly sources (relative to module path).
        let asm_sources: Vec<String> = module
            .asm_sources
            .iter()
            .map(|a| {
                Self::relative_to_module(&module.path, &a.path)
                    .to_string_lossy()
                    .to_string()
            })
            .collect();
        ctx.insert("asm_sources", &asm_sources);

        // Linker scripts (relative to module path).
        let linker_scripts: Vec<String> = module
            .linker_scripts
            .iter()
            .map(|p| {
                Self::relative_to_module(&module.path, p)
                    .to_string_lossy()
                    .to_string()
            })
            .collect();
        ctx.insert("linker_scripts", &linker_scripts);

        // Include directories relative to the module.
        let include_dirs: Vec<String> = module
            .include_dirs
            .iter()
            .map(|d| {
                // If the include dir is the module dir itself, use ".".
                if d == &module.relative_path {
                    ".".into()
                } else {
                    d.to_string_lossy().to_string()
                }
            })
            .collect();
        ctx.insert("include_dirs", &include_dirs);

        // Dependencies with their type.
        let ordered_modules = graph.topological_order().unwrap_or_default();
        let mut sorted_deps = deps.to_vec();
        sorted_deps.sort_by_key(|(name, _)| {
            ordered_modules.iter().position(|n| n == name).unwrap_or(usize::MAX)
        });
        let dep_list: Vec<tera::Value> = sorted_deps
            .iter()
            .map(|(name, dep_type)| {
                let mut m = tera::Map::new();
                m.insert("name".into(), tera::Value::String(name.clone()));
                let type_str = match dep_type {
                    DependencyType::Public => "PUBLIC",
                    DependencyType::Private => "PRIVATE",
                    DependencyType::Interface => "INTERFACE",
                };
                m.insert("type".into(), tera::Value::String(type_str.into()));
                tera::Value::Object(m)
            })
            .collect();
        ctx.insert("dependencies", &dep_list);

        // Compile features — only inject cxx_std_* when the module actually
        // contains C++ sources and the project language is not pure C.
        let has_cpp = module
            .sources
            .iter()
            .any(|s| matches!(s.source_type, crate::models::module::SourceType::CppSource));
        let features: Vec<String> = if module.compile_features.is_empty() {
            if has_cpp && self.config.language != "C" {
                vec![format!("cxx_std_{}", self.config.cpp_standard)]
            } else {
                Vec::new()
            }
        } else {
            module.compile_features.clone()
        };
        ctx.insert("compile_features", &features);

        // Compile definitions.
        ctx.insert("compile_definitions", &module.compile_definitions);

        self.tera
            .render("module", &ctx)
            .map_err(FbGenError::Template)
    }

    /// Augment `deps` with companion source modules for transitive header-only
    /// dependencies.  Walks the dependency tree: whenever a header-only module
    /// has a sibling source module (e.g. `Drivers_..._Inc` ↔ `Drivers_..._Src`),
    /// consumers that transitively depend on the header-only module must also
    /// link the source module so that function implementations are available.
    fn augment_companion_sources(
        deps: &mut Vec<(String, DependencyType)>,
        self_name: &str,
        all_modules: &[CMakeModule],
        graph: &DependencyGraph,
    ) {
        use std::collections::{HashMap, HashSet, VecDeque};

        // Collect companion source modules by first finding header-only
        // modules with sibling source modules.
        let companion_of: HashMap<&str, Vec<String>> = {
            let mut map: HashMap<&str, Vec<String>> = HashMap::new();
            for m in all_modules {
                if m.target_type != TargetType::HeaderOnly {
                    continue;
                }
                let parent = match m.relative_path.parent() {
                    Some(p) => p,
                    None => continue,
                };
                let sources: Vec<String> = all_modules
                    .iter()
                    .filter(|s| {
                        s.target_type == TargetType::StaticLibrary
                            && s.name != m.name
                            && s.relative_path.parent() == Some(parent)
                    })
                    .map(|s| s.name.clone())
                    .collect();
                if !sources.is_empty() {
                    map.insert(m.name.as_str(), sources);
                }
            }
            map
        };

        if companion_of.is_empty() {
            return;
        }

        // BFS over the transitive dependency tree from the module's direct
        // deps, collecting companion source modules along the way.
        let mut seen: HashSet<String> = deps.iter().map(|(n, _)| n.clone()).collect();
        let mut queue: VecDeque<String> = deps.iter().map(|(n, _)| n.clone()).collect();
        let mut extra: Vec<(String, DependencyType)> = Vec::new();

        while let Some(dep_name) = queue.pop_front() {
            // If this dep has companion source modules, add them.
            if let Some(companions) = companion_of.get(dep_name.as_str()) {
                for comp in companions {
                    if comp == self_name {
                        continue;
                    }
                    if seen.insert(comp.clone()) {
                        extra.push((comp.clone(), DependencyType::Public));
                    }
                }
            }

            // Walk the dep's own dependencies transitively.
            for (sub_name, _) in graph.get_dependencies(&dep_name) {
                if seen.insert(sub_name.clone()) {
                    queue.push_back(sub_name);
                }
            }
        }

        deps.extend(extra);
    }

    /// Render the toolchain.cmake content for cross-compilation targets.
    ///
    /// Returns `Ok(None)` if the target architecture does not require a toolchain
    /// (ARM32, ARM64, X86_64, X86, WASM, Custom) or no ToolchainConfig is set.
    ///
    /// Returns `Err` if NoneEabi has no ToolchainConfig or the CPU field is empty.
    fn render_toolchain(&self, root_ld_scripts: &[String]) -> FbGenResult<Option<String>> {
        let tc = match &self.config.toolchain {
            Some(tc) => tc,
            None => {
                // No toolchain config — only valid for non-embedded targets.
                if matches!(&self.config.target_arch, TargetArch::NoneEabi) {
                    return Err(FbGenError::Config(
                        "Toolchain configuration is required for NoneEabi targets. \
                         Run `fb-gen init` to configure."
                            .into(),
                    ));
                }
                return Ok(None);
            }
        };

        // NoneEabi MUST have CPU specified.
        if matches!(&self.config.target_arch, TargetArch::NoneEabi) && tc.cpu.is_empty() {
            return Err(FbGenError::Config(
                "MCU/CPU is required for NoneEabi targets. \
                 Run `fb-gen init` to configure."
                    .into(),
            ));
        }

        match &self.config.target_arch {
            TargetArch::NoneEabi => Ok(Some(self.render_arm_eabi_toolchain(tc, root_ld_scripts)?)),
            TargetArch::ARM32 => {
                if tc.prefix.is_empty() {
                    Ok(None)
                } else {
                    Ok(Some(self.render_embedded_toolchain("Linux", "arm", &tc.prefix, tc, root_ld_scripts)?))
                }
            }
            TargetArch::ARM64 => {
                if tc.prefix.is_empty() {
                    Ok(None)
                } else {
                    Ok(Some(self.render_embedded_toolchain("Linux", "aarch64", &tc.prefix, tc, root_ld_scripts)?))
                }
            }
            TargetArch::RISCV64 => Ok(Some(self.render_riscv64_toolchain(tc, root_ld_scripts)?)),
            _ => Ok(None),
        }
    }

    /// Check whether the user already has a toolchain file that was **not**
    /// generated by fb-gen (e.g. from STM32CubeMX, an IDE, or manual setup).
    ///
    /// Looks first at the `toolchainFile` path in any `CMakePresets.json`
    /// configure preset, then falls back to `cmake/toolchain.cmake`.
    /// Returns `true` when an existing, non-fb-gen toolchain file is found —
    /// in that case fb-gen will **not** generate its own so the user's file
    /// is never overwritten.
    pub(crate) fn user_has_toolchain_file(&self) -> bool {
        // Collect candidate paths to check.
        let mut candidates: Vec<PathBuf> = Vec::new();

        // 1. Preset-specified toolchain file(s).
        if let Some(ref presets) = self.config.cmake_presets {
            for preset in &presets.configure_presets {
                if let Some(ref tf) = preset.toolchain_file {
                    let p = Self::resolve_preset_path(&self.config.root, tf);
                    if !candidates.contains(&p) {
                        candidates.push(p);
                    }
                }
            }
        }

        // 2. Default path.
        let default_path = self.config.root.join("cmake").join("toolchain.cmake");
        if !candidates.contains(&default_path) {
            candidates.push(default_path);
        }

        for path in &candidates {
            if path.exists() {
                if let Ok(content) = fs::read_to_string(path) {
                    // If the file does NOT contain fb-gen's marker, it's user-owned.
                    if !content.contains("Auto-generated toolchain file by fb-gen") {
                        return true;
                    }
                } else {
                    // Unreadable — treat as user-owned to be safe.
                    return true;
                }
            }
        }

        false
    }

    /// Resolve the output path for the fb-gen-generated toolchain file.
    ///
    /// Always returns `cmake/toolchain.cmake` under the project root.
    /// Callers must first check [`user_has_toolchain_file`] — if the user
    /// already has their own toolchain file, fb-gen will not generate one
    /// and this method is never reached.
    #[allow(dead_code)]
    fn resolve_toolchain_path(&self) -> PathBuf {
        self.config.root.join("cmake").join("toolchain.cmake")
    }

    // ── Toolchain helpers ────────────────────────────────────────────────

    /// Resolve a path from a CMakePresets `toolchainFile` string.
    ///
    /// Handles `${sourceDir}` substitution (resolves to the project root),
    /// then joins with `root` if the result is relative.
    pub fn resolve_preset_path(root: &Path, raw: &str) -> PathBuf {
        let resolved = raw.replace("${sourceDir}", &root.to_string_lossy());
        let p = Path::new(&resolved);
        if p.is_absolute() {
            p.to_path_buf()
        } else {
            root.join(p)
        }
    }

    // ── Toolchain rendering methods ─────────────────────────────────────

    /// Render a complete toolchain.cmake for ARM Cortex-M bare-metal targets
    /// (arm-none-eabi-gcc).
    fn render_arm_eabi_toolchain(&self, tc: &ToolchainConfig, root_ld_scripts: &[String]) -> FbGenResult<String> {
        let prefix = if tc.prefix.is_empty() { "arm-none-eabi-" } else { &tc.prefix };
        self.render_embedded_toolchain("Generic", "arm", prefix, tc, root_ld_scripts)
    }

    fn render_riscv64_toolchain(&self, tc: &ToolchainConfig, root_ld_scripts: &[String]) -> FbGenResult<String> {
        let prefix = if tc.prefix.is_empty() { "riscv64-unknown-elf-" } else { &tc.prefix };
        self.render_embedded_toolchain("Generic", "riscv64", prefix, tc, root_ld_scripts)
    }

    /// Render a complete CMake toolchain file using Tera templating.
    fn render_embedded_toolchain(
        &self,
        system_name: &str,
        processor: &str,
        prefix: &str,
        tc: &ToolchainConfig,
        root_ld_scripts: &[String],
    ) -> FbGenResult<String> {
        // Assemble TARGET_FLAGS from structured fields.
        let mut flags: Vec<String> = Vec::new();
        if !tc.cpu.is_empty() {
            flags.push(format!("-mcpu={}", tc.cpu));
        }
        if !tc.float_abi.is_empty() {
            flags.push(format!("-mfloat-abi={}", tc.float_abi));
        }
        if !tc.fpu.is_empty() {
            flags.push(format!("-mfpu={}", tc.fpu));
        }
        if !tc.extra_flags.is_empty() {
            flags.push(tc.extra_flags.clone());
        }
        for define in &tc.device_defines {
            let cleaned = define.strip_prefix("-D").unwrap_or(define);
            if !cleaned.is_empty() {
                flags.push(format!("-D{}", cleaned));
            }
        }
        let target_flags = flags.join(" ");

        let ld_flag = if root_ld_scripts.len() == 1 {
            format!(" -T ${{CMAKE_SOURCE_DIR}}/{}", root_ld_scripts[0])
        } else {
            String::new()
        };

        let mut ctx = Context::new();
        ctx.insert("system_name", system_name);
        ctx.insert("processor", processor);
        ctx.insert("prefix", prefix);
        ctx.insert("target_flags", &target_flags);
        ctx.insert("ld_flag", &ld_flag);
        ctx.insert("sysroot", &tc.sysroot);
        ctx.insert("find_root_path", &tc.find_root_path);

        self.tera
            .render("toolchain", &ctx)
            .map_err(FbGenError::Template)
    }

    // ── Path helpers ─────────────────────────────────────────────────────

    /// Compute a path relative to `module_dir` for `file_path`.
    ///
    /// When the file lives inside the module directory `strip_prefix`
    /// produces the shortest path.  When the file is outside (e.g. a
    /// root-level `startup_*.s` merged into the executable module), the
    /// fallback walks up from `module_dir` to find a common ancestor and
    /// produces a `../`-style relative path that CMake can resolve.
    fn relative_to_module(module_dir: &Path, file_path: &Path) -> PathBuf {
        // Common case: file is inside the module directory.
        if let Ok(rel) = file_path.strip_prefix(module_dir) {
            return rel.to_path_buf();
        }

        // Walk up from module_dir until we find a common ancestor.
        let mut up = PathBuf::new();
        let mut current = module_dir.to_path_buf();
        loop {
            match current.parent() {
                Some(parent) => {
                    current = parent.to_path_buf();
                    up.push("..");
                }
                None => {
                    // No common ancestor — fall back to the file name.
                    return file_path
                        .file_name()
                        .map(Path::new)
                        .map(Path::to_path_buf)
                        .unwrap_or_else(|| file_path.to_path_buf());
                }
            }
            if let Ok(rel) = file_path.strip_prefix(&current) {
                up.push(rel);
                return up;
            }
        }
    }

    /// Write content to `dest`, respecting the overwrite / merge strategy.
    ///
    /// * `force=true` — overwrite directly (init mode).
    /// * `force=false` — write to `.new` if file exists and differs (sync mode).
    fn write_if_changed(
        &self,
        dest: &Path,
        new_content: &str,
        label: &str,
        force: bool,
    ) -> FbGenResult<()> {
        if dest.exists() {
            let existing = fs::read_to_string(dest).map_err(FbGenError::Io)?;

            // Extract USER_START / USER_END blocks from the existing file.
            let user_block = extract_user_block(&existing);

            // Merge user block into the new content if one exists.
            let merged = if let Some(block) = &user_block {
                merge_user_block(new_content, block)
            } else {
                new_content.to_string()
            };

            if merged.trim() == existing.trim() {
                // Content identical — nothing to do.
                return Ok(());
            }

            if force {
                // Overwrite directly (init mode).
                let content_to_write = if user_block.is_some() {
                    &merged
                } else {
                    new_content
                };
                fs::write(dest, content_to_write).map_err(FbGenError::Io)?;
                eprintln!("fb-gen: {} CMakeLists.txt overwritten (force mode)", label);
            } else {
                // Write .new file instead (sync mode).
                let new_path = if let Some(stem) = dest.file_stem() {
                    let mut p = dest.to_path_buf();
                    p.set_file_name(format!("{}.new", stem.to_string_lossy()));
                    if let Some(ext) = dest.extension() {
                        p.set_extension(format!("{}.new", ext.to_string_lossy()));
                    }
                    p
                } else {
                    dest.with_extension("new")
                };

                if user_block.is_some() {
                    fs::write(&new_path, &merged).map_err(FbGenError::Io)?;
                } else {
                    fs::write(&new_path, new_content).map_err(FbGenError::Io)?;
                }

                eprintln!(
                    "fb-gen: {} CMakeLists.txt already exists and differs — wrote {}",
                    label,
                    new_path.display()
                );
                eprintln!("fb-gen:   diff {} {}", dest.display(), new_path.display());
            }
        } else {
            // File doesn't exist — write directly.
            // Ensure parent directory exists.
            if let Some(parent) = dest.parent() {
                fs::create_dir_all(parent).map_err(FbGenError::Io)?;
            }
            fs::write(dest, new_content).map_err(FbGenError::Io)?;
        }

        Ok(())
    }
}


/// Scan the project root (non-recursive) for `.ld` linker scripts.
///
/// Returns the detected linker script file names (basenames only).
/// When exactly one `.ld` file is found at the root, it is used in the
/// toolchain file.  Zero or multiple `.ld` files → empty vec.
fn detect_linker_scripts(root: &Path) -> Vec<String> {
    let mut found: Vec<String> = Vec::new();
    let entries = match std::fs::read_dir(root) {
        Ok(e) => e,
        Err(_) => return found,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file() {
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if ext.eq_ignore_ascii_case("ld") {
                    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                        found.push(name.to_string());
                    }
                }
            }
        }
    }
    if found.len() == 1 { found } else { Vec::new() }
}

// ── Cross-compilation helpers ──────────────────────────────────────────────

/// Returns the cross-compilation context tuple:
/// `(is_cross, system_name, system_processor, c_compiler, cxx_compiler, asm_compiler, linker_flags)`
#[allow(dead_code)]
fn cross_compile_context(
    arch: &TargetArch,
) -> (bool, String, String, String, String, String, String) {
    match arch {
        TargetArch::NoneEabi => (
            true,
            "Generic".into(),
            "arm".into(),
            "arm-none-eabi-gcc".into(),
            "arm-none-eabi-g++".into(),
            "arm-none-eabi-gcc".into(),
            String::new(),
        ),
        TargetArch::ARM32 => (
            true,
            "Generic".into(),
            "arm".into(),
            "arm-none-eabi-gcc".into(),
            "arm-none-eabi-g++".into(),
            "arm-none-eabi-gcc".into(),
            String::new(),
        ),
        TargetArch::ARM64 => (
            true,
            "Generic".into(),
            "aarch64".into(),
            "aarch64-none-elf-gcc".into(),
            "aarch64-none-elf-g++".into(),
            "aarch64-none-elf-gcc".into(),
            String::new(),
        ),
        TargetArch::RISCV64 => (
            true,
            "Generic".into(),
            "riscv64".into(),
            "riscv64-unknown-elf-gcc".into(),
            "riscv64-unknown-elf-g++".into(),
            "riscv64-unknown-elf-gcc".into(),
            String::new(),
        ),
        TargetArch::WASM => (
            true,
            "Generic".into(),
            "wasm32".into(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        ),
        // Custom and non-cross targets.
        TargetArch::Custom(_) => (
            false,
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        ),
        TargetArch::X86_64 | TargetArch::X86 => (
            false,
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
            String::new(),
        ),
    }
}

// ── User-block helpers ─────────────────────────────────────────────────────

/// Extract the content between `# USER_START` and `# USER_END` markers.
///
/// Returns `None` if the markers are not present.
fn extract_user_block(content: &str) -> Option<String> {
    let start_marker = "# USER_START";
    let end_marker = "# USER_END";

    let start = content.find(start_marker)?;
    let after_start = &content[start + start_marker.len()..];
    let end = after_start.find(end_marker)?;

    let block = after_start[..end].trim();
    if block.is_empty() {
        None
    } else {
        Some(block.to_string())
    }
}

/// Merge a user block into freshly generated content by replacing the
/// `# USER_START\n# USER_END` placeholder with the preserved block.
fn merge_user_block(template: &str, user_block: &str) -> String {
    let placeholder = "# USER_START\n# USER_END";
    let replacement = format!("# USER_START\n{}\n# USER_END", user_block.trim());

    // Also handle the case where there's content between markers in the
    // template (shouldn't happen with our templates, but be safe).
    if template.contains(placeholder) {
        template.replace(placeholder, &replacement)
    } else {
        // Fallback: find the markers and replace the block between them.
        let start_marker = "# USER_START";
        let end_marker = "# USER_END";

        if let (Some(start), Some(end)) = (template.find(start_marker), template.find(end_marker)) {
            let before = &template[..start + start_marker.len()];
            let after = &template[end..];
            format!("{}\n{}\n{}", before, user_block.trim(), after)
        } else {
            // No markers in template — append at end.
            format!("{}\n{}", template, replacement)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_user_block_present() {
        let content = "line 1\n# USER_START\nset(MY_VAR ON)\n# USER_END\nline 5";
        let block = extract_user_block(content);
        assert_eq!(block, Some("set(MY_VAR ON)".into()));
    }

    #[test]
    fn test_extract_user_block_absent() {
        let content = "line 1\nline 2";
        assert_eq!(extract_user_block(content), None);
    }

    #[test]
    fn test_extract_user_block_empty() {
        let content = "line 1\n# USER_START\n# USER_END\nline 3";
        assert_eq!(extract_user_block(content), None); // empty → None
    }

    #[test]
    fn test_merge_user_block() {
        let template = "before\n# USER_START\n# USER_END\nafter";
        let merged = merge_user_block(template, "set(FOO ON)");
        assert_eq!(
            merged,
            "before\n# USER_START\nset(FOO ON)\n# USER_END\nafter"
        );
    }

    #[test]
    fn test_cross_compile_context_x86_64() {
        let (is_cross, _name, _proc, _cc, _cxx, _asm, _ld) =
            cross_compile_context(&TargetArch::X86_64);
        assert!(!is_cross);
        assert!(_name.is_empty());
        assert!(_cc.is_empty());
    }

    #[test]
    fn test_cross_compile_context_arm32() {
        let (is_cross, _name, _proc, _cc, _cxx, _asm, _ld) =
            cross_compile_context(&TargetArch::ARM32);
        assert!(is_cross);
        assert_eq!(_name, "Generic");
        assert_eq!(_proc, "arm");
        assert_eq!(_cc, "arm-none-eabi-gcc");
        assert_eq!(_cxx, "arm-none-eabi-g++");
        assert_eq!(_asm, "arm-none-eabi-gcc");
    }

    #[test]
    fn test_cross_compile_context_arm64() {
        let (is_cross, _name, _proc, _cc, _cxx, _asm, _ld) =
            cross_compile_context(&TargetArch::ARM64);
        assert!(is_cross);
        assert_eq!(_proc, "aarch64");
        assert_eq!(_cc, "aarch64-none-elf-gcc");
    }

    #[test]
    fn test_cross_compile_context_riscv64() {
        let (is_cross, _name, _proc, _cc, _cxx, _asm, _ld) =
            cross_compile_context(&TargetArch::RISCV64);
        assert!(is_cross);
        assert_eq!(_proc, "riscv64");
        assert_eq!(_cc, "riscv64-unknown-elf-gcc");
    }

    #[test]
    fn test_cross_compile_context_wasm() {
        let (is_cross, _name, _proc, _cc, _cxx, _asm, _ld) =
            cross_compile_context(&TargetArch::WASM);
        assert!(is_cross);
        assert_eq!(_proc, "wasm32");
        assert!(_cc.is_empty()); // WASM doesn't set C compiler
        assert!(_cxx.is_empty());
    }

    #[test]
    fn test_cross_compile_context_none_eabi() {
        let (is_cross, _name, _proc, _cc, _cxx, _asm, _ld) =
            cross_compile_context(&TargetArch::NoneEabi);
        assert!(is_cross);
        assert_eq!(_proc, "arm");
        assert_eq!(_cc, "arm-none-eabi-gcc");
    }
}
