//! Zig build system generator — produces `build.zig` from module and
//! dependency data.
//!
//! Activated when `ProjectConfig::build_system == BuildSystem::Zig`.
//! Completely independent of the CMake code path.

use crate::models::dependency::DependencyGraph;
use crate::models::error::{FbGenError, FbGenResult};
use crate::models::module::{CMakeModule, SourceType, TargetType};
use crate::models::project::{ProjectConfig, TargetArch};
use std::fs;
use std::path::PathBuf;

// ── Zig target descriptor ───────────────────────────────────────────────────

/// A resolved Zig target: separates the CPU architecture enum variant from
/// the module path where CPU models are defined.
///
/// Zig organises CPU models under `<module>.cpu.<name>`.  The module does
/// *not* always match the arch enum variant — e.g. `x86_64` models live
/// under `std.Target.x86`, `riscv32` models under `std.Target.riscv`.
struct ZigTarget {
    /// Zig module name for CPU model paths (e.g. `"x86"`, `"arm"`, `"riscv"`).
    target_module: &'static str,
    /// Zig `cpu_arch` enum variant (e.g. `.x86_64`, `.thumb`, `.riscv32`).
    cpu_arch: &'static str,
    /// Default CPU model name under `std.Target.<module>.cpu.<name>`.
    default_cpu: &'static str,
    /// Zig `os_tag` enum variant (`.linux`, `.freestanding`).
    os_tag: &'static str,
    /// Zig `abi` enum variant (`.gnu`, `.none`, …).
    abi: &'static str,
}

fn zig_target(arch: &TargetArch) -> ZigTarget {
    match arch {
        // ── Native / Linux targets ──────────────────────────────────
        TargetArch::X86_64 => ZigTarget {
            target_module: "x86", cpu_arch: "x86_64", default_cpu: "native",
            os_tag: "linux", abi: "gnu",
        },
        TargetArch::X86 => ZigTarget {
            target_module: "x86", cpu_arch: "x86", default_cpu: "native",
            os_tag: "linux", abi: "gnu",
        },
        // ── ARM ────────────────────────────────────────────────────
        // `thumb` is the arch used for Cortex-M; CPU models are in
        // `std.Target.arm.cpu.*`.
        TargetArch::NoneEabi => ZigTarget {
            target_module: "arm", cpu_arch: "thumb", default_cpu: "cortex_m3",
            os_tag: "freestanding", abi: "none",
        },
        TargetArch::ARM32 => ZigTarget {
            target_module: "arm", cpu_arch: "arm", default_cpu: "generic",
            os_tag: "freestanding", abi: "none",
        },
        // ── AArch64 ────────────────────────────────────────────────
        TargetArch::ARM64 => ZigTarget {
            target_module: "aarch64", cpu_arch: "aarch64", default_cpu: "generic",
            os_tag: "freestanding", abi: "none",
        },
        // ── RISC-V — all models under `std.Target.riscv.cpu.*` ─────
        TargetArch::RISCV64 => ZigTarget {
            target_module: "riscv", cpu_arch: "riscv64", default_cpu: "generic_rv64",
            os_tag: "freestanding", abi: "none",
        },
        TargetArch::RISCV32 => ZigTarget {
            target_module: "riscv", cpu_arch: "riscv32", default_cpu: "generic_rv32",
            os_tag: "freestanding", abi: "none",
        },
        // ── Xtensa (ESP32) — only `generic` model exists ───────────
        TargetArch::Xtensa => ZigTarget {
            target_module: "xtensa", cpu_arch: "xtensa", default_cpu: "generic",
            os_tag: "freestanding", abi: "none",
        },
        // ── WASM — models under `std.Target.wasm.cpu.*` ────────────
        TargetArch::WASM => ZigTarget {
            target_module: "wasm", cpu_arch: "wasm32", default_cpu: "generic",
            os_tag: "freestanding", abi: "none",
        },
        // ── Custom — assume native ─────────────────────────────────
        TargetArch::Custom(_) => ZigTarget {
            target_module: "x86", cpu_arch: "x86_64", default_cpu: "native",
            os_tag: "linux", abi: "gnu",
        },
    }
}

// ── Template ─────────────────────────────────────────────────────────────────
//
// Follows the Zig 0.16 build system API:
//   - `b.standardTargetOptions(.{})` for native (user-overridable).
//   - `b.resolveTargetQuery(.{...})` for cross / embedded (locked target).
//   - `b.createModule(.{ .target, .optimize, .link_libc?, .link_libcpp? })`.
//   - `b.addExecutable(.{ .name, .root_module })`.
//   - `b.addLibrary(.{ .name, .linkage = .static, .root_module })`.
//   - `mod.addCSourceFiles(.{ .files, .flags })`.
//   - `mod.addIncludePath(b.path(...))`.
//   - `mod.linkLibrary(...)`.

const ZIG_BUILD_TEMPLATE: &str = r#"// Auto-generated by fb-gen — do not edit manually.
const std = @import("std");

pub fn build(b: *std.Build) void {
{% if is_cross -%}
    // Cross-compilation: locked target (not overridable via -Dtarget).
    const target = b.resolveTargetQuery(.{
        .cpu_arch = .{{ cpu_arch }},
        .cpu_model = .{ .explicit = &std.Target.{{ target_module }}.cpu.{{ cpu_model }} },
        .os_tag = .{{ os_tag }},
        .abi = .{{ abi }},
    });
{% else -%}
    // Native: user-overridable via -Dtarget= / -Dcpu=.
    const target = b.standardTargetOptions(.{});
{% endif -%}
    const optimize = b.standardOptimizeOption(.{
        .preferred_optimize_mode = .{{ optimize }},
    });

    // ── Modules ──────────────────────────────────────────────
{% for mod in modules -%}
{% if mod.is_executable -%}
    // Executable: {{ mod.name }}
    const {{ mod.name_safe }}_mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
{% if mod.link_libc -%}
        .link_libc = true,
{% endif -%}
{% if mod.link_libcpp -%}
        .link_libcpp = true,
{% endif -%}
    });
{% if mod.sources | length > 0 -%}
    {{ mod.name_safe }}_mod.addCSourceFiles(.{
        .files = &.{ {% for src in mod.sources -%}"{{ src }}", {% endfor -%} },
        .flags = &.{ {% for flag in mod.compile_flags -%}"{{ flag }}", {% endfor -%} },
    });
{% endif -%}
{% for asm in mod.asm_sources -%}
    {{ mod.name_safe }}_mod.addCSourceFile(.{ .file = b.path("{{ asm }}"), .flags = &.{"-x", "assembler-with-cpp"} });
{% endfor -%}
    {{ mod.name_safe }}_mod.addIncludePath(b.path("{{ mod.path }}"));
{% for inc in mod.include_dirs -%}
    {{ mod.name_safe }}_mod.addIncludePath(b.path("{{ inc }}"));
{% endfor -%}
{% for def in mod.compile_definitions -%}
    {{ mod.name_safe }}_mod.addCMacro("{{ def.name }}", "{{ def.value }}");
{% endfor -%}
{% if mod.linker_script -%}
    {{ mod.name_safe }}.setLinkerScript(b.path("{{ mod.linker_script }}"));
{% endif -%}
    const {{ mod.name_safe }} = b.addExecutable(.{
        .name = "{{ mod.name }}",
        .root_module = {{ mod.name_safe }}_mod,
    });

{% else -%}
    // Library: {{ mod.name }}
    const {{ mod.name_safe }}_mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
{% if mod.link_libc -%}
        .link_libc = true,
{% endif -%}
{% if mod.link_libcpp -%}
        .link_libcpp = true,
{% endif -%}
    });
{% if mod.sources | length > 0 -%}
    {{ mod.name_safe }}_mod.addCSourceFiles(.{
        .files = &.{ {% for src in mod.sources -%}"{{ src }}", {% endfor -%} },
        .flags = &.{ {% for flag in mod.compile_flags -%}"{{ flag }}", {% endfor -%} },
    });
{% endif -%}
{% for asm in mod.asm_sources -%}
    {{ mod.name_safe }}_mod.addCSourceFile(.{ .file = b.path("{{ asm }}"), .flags = &.{"-x", "assembler-with-cpp"} });
{% endfor -%}
    {{ mod.name_safe }}_mod.addIncludePath(b.path("{{ mod.path }}"));
{% for inc in mod.include_dirs -%}
    {{ mod.name_safe }}_mod.addIncludePath(b.path("{{ inc }}"));
{% endfor -%}
{% for def in mod.compile_definitions -%}
    {{ mod.name_safe }}_mod.addCMacro("{{ def.name }}", "{{ def.value }}");
{% endfor -%}
{% if mod.linker_script -%}
    {{ mod.name_safe }}.setLinkerScript(b.path("{{ mod.linker_script }}"));
{% endif -%}
    const {{ mod.name_safe }} = b.addLibrary(.{
        .name = "{{ mod.name }}",
        .linkage = .static,
        .root_module = {{ mod.name_safe }}_mod,
    });

{% endif -%}
{% endfor -%}
    // ── Module dependencies ────────────────────────────────────
{% for edge in dependencies -%}
    {{ edge.from_safe }}_mod.addIncludePath(b.path("{{ edge.to_path }}"));
    {{ edge.from_safe }}_mod.linkLibrary({{ edge.to_safe }});
{% endfor -%}

    // ── Install ──────────────────────────────────────────────
{% for mod in modules -%}
{% if mod.is_executable -%}
    b.installArtifact({{ mod.name_safe }});
{% endif -%}
{% endfor -%}
}
"#;

// ── Generator ────────────────────────────────────────────────────────────────

pub struct ZigGenerator {
    config: ProjectConfig,
}

impl ZigGenerator {
    pub fn new(config: &ProjectConfig) -> FbGenResult<Self> {
        Ok(Self {
            config: config.clone(),
        })
    }

    fn needs_libc(arch: &TargetArch) -> bool {
        matches!(arch, TargetArch::X86_64 | TargetArch::X86)
    }

    fn resolve_cpu_model(&self, target: &ZigTarget) -> String {
        self.config
            .toolchain
            .as_ref()
            .and_then(|tc| {
                if tc.cpu.is_empty() {
                    None
                } else {
                    Some(tc.cpu.clone())
                }
            })
            .unwrap_or_else(|| target.default_cpu.to_string())
    }

    fn module_has_cxx(m: &CMakeModule) -> bool {
        m.sources
            .iter()
            .any(|s| matches!(s.source_type, SourceType::CppSource | SourceType::CppHeader))
    }

    fn split_define(def: &str) -> (&str, &str) {
        match def.split_once('=') {
            Some((name, value)) => (name, value),
            None => (def, ""),
        }
    }

    /// Generate `build.zig` at the project root.
    pub fn generate(
        &self,
        modules: &[CMakeModule],
        graph: &DependencyGraph,
        _force: bool,
        _user_modules: &[PathBuf],
    ) -> FbGenResult<()> {
        let target = zig_target(&self.config.target_arch);
        let is_cross = target.os_tag == "freestanding";
        let cpu_model = self.resolve_cpu_model(&target);
        let has_libc = Self::needs_libc(&self.config.target_arch);
        let has_libcpp = self.config.language == "CXX"
            || modules.iter().any(Self::module_has_cxx);

        let optimize = if is_cross { "ReleaseSmall" } else { "Debug" };

        let mut tera = tera::Tera::default();
        tera.add_raw_template("zig", ZIG_BUILD_TEMPLATE)
            .map_err(FbGenError::Template)?;

        let mut ctx = tera::Context::new();
        ctx.insert("is_cross", &is_cross);
        ctx.insert("target_module", target.target_module);
        ctx.insert("cpu_arch", target.cpu_arch);
        ctx.insert("cpu_model", &cpu_model);
        ctx.insert("os_tag", target.os_tag);
        ctx.insert("abi", target.abi);
        ctx.insert("optimize", optimize);

        let mut mod_ctxs: Vec<serde_json::Value> = Vec::new();
        for m in modules {
            let source_paths: Vec<String> = m
                .sources.iter()
                .map(|s| s.relative_path.to_string_lossy().to_string())
                .collect();
            let asm_paths: Vec<String> = m
                .asm_sources.iter()
                .map(|s| s.path.to_string_lossy().to_string())
                .collect();
            let include_dirs: Vec<String> = m
                .include_dirs.iter()
                .map(|d| d.to_string_lossy().to_string())
                .collect();
            let defines: Vec<serde_json::Value> = m
                .compile_definitions.iter()
                .map(|d| {
                    let (name, value) = Self::split_define(d);
                    serde_json::json!({ "name": name, "value": value })
                })
                .collect();
            let is_executable = (m.has_main || m.is_root)
                && !m.sources.is_empty()
                && m.target_type != TargetType::HeaderOnly;
            let linker_script = m.linker_scripts.first().map(|p| p.to_string_lossy().to_string());

            mod_ctxs.push(serde_json::json!({
                "name": m.name,
                "name_safe": sanitize_name(&m.name),
                "path": m.relative_path.to_string_lossy().to_string(),
                "is_executable": is_executable,
                "sources": source_paths,
                "asm_sources": asm_paths,
                "compile_flags": Vec::<String>::new(),
                "include_dirs": include_dirs,
                "compile_definitions": defines,
                "link_libc": has_libc,
                "link_libcpp": has_libcpp && Self::module_has_cxx(m),
                "linker_script": linker_script,
            }));
        }
        ctx.insert("modules", &mod_ctxs);

        let mut dep_ctxs: Vec<serde_json::Value> = Vec::new();
        for m in modules {
            let from_safe = sanitize_name(&m.name);
            let deps = graph.get_dependencies(&m.name);
            for (dep_name, _dep_type) in &deps {
                let to_path = modules
                    .iter()
                    .find(|modu| &modu.name == dep_name)
                    .map(|modu| modu.relative_path.to_string_lossy().to_string())
                    .unwrap_or_default();
                dep_ctxs.push(serde_json::json!({
                    "from_safe": from_safe,
                    "to_safe": sanitize_name(dep_name),
                    "to_path": to_path,
                }));
            }
        }
        ctx.insert("dependencies", &dep_ctxs);

        let rendered = tera.render("zig", &ctx).map_err(FbGenError::Template)?;

        let dest = self.config.root.join("build.zig");
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent).map_err(FbGenError::Io)?;
        }
        fs::write(&dest, rendered).map_err(FbGenError::Io)?;

        Ok(())
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn sanitize_name(name: &str) -> String {
    name.replace('-', "_")
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::project::BuildSystem;

    // ── zig_target ────────────────────────────────────────────────────

    #[test]
    fn test_zig_target_x86_64() {
        let t = zig_target(&TargetArch::X86_64);
        assert_eq!(t.target_module, "x86");
        assert_eq!(t.cpu_arch, "x86_64");
        assert_eq!(t.os_tag, "linux");
        assert_eq!(t.abi, "gnu");
    }

    #[test]
    fn test_zig_target_thumb() {
        let t = zig_target(&TargetArch::NoneEabi);
        assert_eq!(t.target_module, "arm");
        assert_eq!(t.cpu_arch, "thumb");
        assert_eq!(t.default_cpu, "cortex_m3");
        assert_eq!(t.os_tag, "freestanding");
        assert_eq!(t.abi, "none");
    }

    #[test]
    fn test_zig_target_riscv32() {
        let t = zig_target(&TargetArch::RISCV32);
        assert_eq!(t.target_module, "riscv");
        assert_eq!(t.cpu_arch, "riscv32");
        assert_eq!(t.default_cpu, "generic_rv32");
    }

    #[test]
    fn test_zig_target_riscv64() {
        let t = zig_target(&TargetArch::RISCV64);
        assert_eq!(t.target_module, "riscv");
        assert_eq!(t.cpu_arch, "riscv64");
        assert_eq!(t.default_cpu, "generic_rv64");
    }

    #[test]
    fn test_zig_target_xtensa_generic_only() {
        let t = zig_target(&TargetArch::Xtensa);
        assert_eq!(t.target_module, "xtensa");
        assert_eq!(t.default_cpu, "generic"); // only model that exists
    }

    #[test]
    fn test_zig_target_wasm() {
        let t = zig_target(&TargetArch::WASM);
        assert_eq!(t.target_module, "wasm");
        assert_eq!(t.cpu_arch, "wasm32");
    }

    #[test]
    fn test_cross_detection() {
        assert!(!zig_target(&TargetArch::X86_64).os_tag.contains("freestanding"));
        assert!(zig_target(&TargetArch::Xtensa).os_tag.contains("freestanding"));
    }

    // ── helpers ───────────────────────────────────────────────────────

    #[test]
    fn test_split_define() {
        assert_eq!(ZigGenerator::split_define("FOO=bar"), ("FOO", "bar"));
        assert_eq!(ZigGenerator::split_define("DEBUG"), ("DEBUG", ""));
        assert_eq!(ZigGenerator::split_define("A=B=C"), ("A", "B=C"));
    }

    #[test]
    fn test_needs_libc_only_for_linux() {
        assert!(ZigGenerator::needs_libc(&TargetArch::X86_64));
        assert!(!ZigGenerator::needs_libc(&TargetArch::NoneEabi));
    }

    // ── integration ──────────────────────────────────────────────────

    #[test]
    fn test_generate_does_not_panic() {
        let tmp = tempfile::tempdir().unwrap();
        let config = ProjectConfig {
            name: "test_zig".into(),
            root: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let gen = ZigGenerator::new(&config).unwrap();
        let result = gen.generate(&[], &DependencyGraph::new(), true, &[]);
        assert!(result.is_ok());
        assert!(tmp.path().join("build.zig").exists());
    }

    #[test]
    fn test_build_system_default_is_cmake() {
        assert_eq!(BuildSystem::default(), BuildSystem::CMake);
    }
}
