//! Zig build system generator — produces `build.zig` from module and
//! dependency data.
//!
//! Activated when `ProjectConfig::build_system == BuildSystem::Zig`.
//! Completely independent of the CMake code path — no shared types beyond
//! the generic `CMakeModule` / `DependencyGraph` models.

use crate::models::dependency::DependencyGraph;
use crate::models::error::{FbGenError, FbGenResult};
use crate::models::module::CMakeModule;
use crate::models::project::{ProjectConfig, TargetArch};
use std::fs;
use std::path::PathBuf;

// ── Zig 0.16 build.zig template ─────────────────────────────────────────────
//
// Uses the current (0.16) build system API:
//   - b.standardTargetOptions(.{}) / b.standardOptimizeOption(.{})
//   - b.createModule(.{ .target, .optimize, .link_libc, ... })
//   - mod.addCSourceFiles(.{ .files, .flags })  ← on the module, not the step
//   - b.addExecutable(.{ .name, .root_module }) / b.addLibrary(.{ ... })
//   - b.path(...) for all LazyPath values
//   - addIncludePath(b.path(...)) / linkLibrary(...)

const ZIG_BUILD_TEMPLATE: &str = r#"// Auto-generated by fb-gen — do not edit manually.
const std = @import("std");

pub fn build(b: *std.Build) void {
{% if is_cross -%}
    const target = b.standardTargetOptions(.{
        .default_target = b.resolveTargetQuery(.{
            .cpu_arch = .{{ cpu_arch }},
            .cpu_model = .{ .explicit = &std.Target.{{ cpu_arch }}.cpu.{{ cpu_model }} },
            .os_tag = .{{ os_tag }},
        }),
    });
{% else -%}
    const target = b.standardTargetOptions(.{});
{% endif -%}
    const optimize = b.standardOptimizeOption(.{
        .preferred_optimize_mode = .{{ optimize }},
    });

    // ── Modules ──────────────────────────────────────────────
{% for mod in modules -%}
{% if mod.is_executable -%}
    // Executable: {{ mod.name }}
    const {{ mod.name_safe }}_mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    {{ mod.name_safe }}_mod.addCSourceFiles(.{
        .files = &.{ {% for src in mod.sources -%}"{{ src }}", {% endfor -%} },
        .flags = &.{ {% for flag in mod.compile_flags -%}"{{ flag }}", {% endfor -%} },
    });
    {{ mod.name_safe }}_mod.addIncludePath(b.path("{{ mod.path }}"));
{% for inc in mod.include_dirs -%}
    {{ mod.name_safe }}_mod.addIncludePath(b.path("{{ inc }}"));
{% endfor -%}
{% for def in mod.compile_definitions -%}
    {{ mod.name_safe }}_mod.addCMacro("{{ def }}");
{% endfor -%}
    const {{ mod.name_safe }} = b.addExecutable(.{
        .name = "{{ mod.name }}",
        .root_module = {{ mod.name_safe }}_mod,
    });

{% else -%}
    // Library: {{ mod.name }}
    const {{ mod.name_safe }}_mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    {{ mod.name_safe }}_mod.addCSourceFiles(.{
        .files = &.{ {% for src in mod.sources -%}"{{ src }}", {% endfor -%} },
        .flags = &.{ {% for flag in mod.compile_flags -%}"{{ flag }}", {% endfor -%} },
    });
    {{ mod.name_safe }}_mod.addIncludePath(b.path("{{ mod.path }}"));
{% for inc in mod.include_dirs -%}
    {{ mod.name_safe }}_mod.addIncludePath(b.path("{{ inc }}"));
{% endfor -%}
{% for def in mod.compile_definitions -%}
    {{ mod.name_safe }}_mod.addCMacro("{{ def }}");
{% endfor -%}
    const {{ mod.name_safe }} = b.addLibrary(.{
        .name = "{{ mod.name }}",
        .linkage = .static,
        .root_module = {{ mod.name_safe }}_mod,
    });

{% endif -%}
{% endfor -%}
    // ── Module dependencies ────────────────────────────────────
    // Each consumer's module gets the provider's include path
    // and links against the provider's library.
{% for edge in dependencies -%}
    {{ edge.from_safe }}_mod.addIncludePath(b.path("{{ edge.to_path }}"));
    {{ edge.from_safe }}_mod.linkLibrary({{ edge.to_safe }});
{% endfor -%}

    // ── Install ──────────────────────────────────────────────
{% for mod in modules -%}
{% if mod.is_executable -%}
    b.installArtifact({{ mod.name_safe }});
{% endif -%}
{% endfor -%}
}
"#;

// ── Generator ────────────────────────────────────────────────────────────────

/// Produces `build.zig` at the project root.  Does not reference any CMake
/// types or templates — completely independent code path.
pub struct ZigGenerator {
    config: ProjectConfig,
}

impl ZigGenerator {
    pub fn new(config: &ProjectConfig) -> FbGenResult<Self> {
        Ok(Self {
            config: config.clone(),
        })
    }

    /// Map a `TargetArch` to a Zig target tuple:
    /// `(cpu_arch_str, os_tag_str, default_cpu_model)`.
    pub fn map_target(arch: &TargetArch) -> (&'static str, &'static str, &'static str) {
        match arch {
            TargetArch::X86_64 => ("x86_64", "linux", "native"),
            TargetArch::X86 => ("x86", "linux", "native"),
            TargetArch::ARM32 => ("arm", "freestanding", "generic"),
            TargetArch::ARM64 => ("aarch64", "freestanding", "generic"),
            TargetArch::NoneEabi => ("thumb", "freestanding", "generic"),
            TargetArch::RISCV64 => ("riscv64", "freestanding", "baseline_rv64"),
            TargetArch::RISCV32 => ("riscv32", "freestanding", "baseline_rv32"),
            TargetArch::Xtensa => ("xtensa", "freestanding", "esp32s3"),
            TargetArch::WASM => ("wasm32", "freestanding", "baseline"),
            TargetArch::Custom(_) => ("x86_64", "linux", "native"),
        }
    }

    /// Whether this is a cross-compilation target (needs explicit
    /// `resolveTargetQuery` in the generated build.zig).
    fn is_cross(arch: &TargetArch) -> bool {
        !matches!(arch, TargetArch::X86_64 | TargetArch::X86)
    }

    /// Resolve the actual CPU model: use `ToolchainConfig.cpu` if set,
    /// otherwise fall back to the architecture default.
    fn resolve_cpu_model(&self, default_model: &str) -> String {
        self.config
            .toolchain
            .as_ref()
            .and_then(|tc| {
                if tc.cpu.is_empty() {
                    None
                } else {
                    Some(tc.cpu.clone())
                }
            })
            .unwrap_or_else(|| default_model.to_string())
    }

    /// Generate `build.zig` at the project root.
    pub fn generate(
        &self,
        modules: &[CMakeModule],
        graph: &DependencyGraph,
        _force: bool,
        _user_modules: &[PathBuf],
    ) -> FbGenResult<()> {
        let (cpu_arch, os_tag, default_cpu) = Self::map_target(&self.config.target_arch);
        let cpu_model = self.resolve_cpu_model(default_cpu);
        let is_cross = Self::is_cross(&self.config.target_arch);

        let optimize = match self.config.target_arch {
            TargetArch::X86_64 | TargetArch::X86 | TargetArch::Custom(_) => "Debug",
            _ => "ReleaseSmall",
        };

        // ── Render via Tera ──────────────────────────────────────────
        let mut tera = tera::Tera::default();
        tera.add_raw_template("zig", ZIG_BUILD_TEMPLATE)
            .map_err(FbGenError::Template)?;

        let mut ctx = tera::Context::new();
        ctx.insert("is_cross", &is_cross);
        ctx.insert("cpu_arch", cpu_arch);
        ctx.insert("cpu_model", &cpu_model);
        ctx.insert("os_tag", os_tag);
        ctx.insert("optimize", optimize);

        let mut mod_ctxs: Vec<serde_json::Value> = Vec::new();
        for m in modules {
            let source_paths: Vec<String> = m
                .sources
                .iter()
                .map(|s| s.relative_path.to_string_lossy().to_string())
                .collect();
            let include_dirs: Vec<String> = m
                .include_dirs
                .iter()
                .map(|d| d.to_string_lossy().to_string())
                .collect();
            mod_ctxs.push(serde_json::json!({
                "name": m.name,
                "name_safe": sanitize_name(&m.name),
                "path": m.relative_path.to_string_lossy().to_string(),
                "is_executable": m.has_main || m.is_root,
                "sources": source_paths,
                "compile_flags": Vec::<String>::new(),
                "include_dirs": include_dirs,
                "compile_definitions": &m.compile_definitions,
            }));
        }
        ctx.insert("modules", &mod_ctxs);

        let mut dep_ctxs: Vec<serde_json::Value> = Vec::new();
        for m in modules {
            let from_safe = sanitize_name(&m.name);
            let deps = graph.get_dependencies(&m.name);
            for (dep_name, _dep_type) in &deps {
                let to_path = modules
                    .iter()
                    .find(|modu| &modu.name == dep_name)
                    .map(|modu| modu.relative_path.to_string_lossy().to_string())
                    .unwrap_or_default();
                dep_ctxs.push(serde_json::json!({
                    "from_safe": from_safe,
                    "to_safe": sanitize_name(dep_name),
                    "to_path": to_path,
                }));
            }
        }
        ctx.insert("dependencies", &dep_ctxs);

        let rendered = tera.render("zig", &ctx).map_err(FbGenError::Template)?;

        let dest = self.config.root.join("build.zig");
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent).map_err(FbGenError::Io)?;
        }
        fs::write(&dest, rendered).map_err(FbGenError::Io)?;

        Ok(())
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn sanitize_name(name: &str) -> String {
    name.replace('-', "_")
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::project::BuildSystem;

    #[test]
    fn test_map_target_xtensa() {
        let (arch, os, cpu) = ZigGenerator::map_target(&TargetArch::Xtensa);
        assert_eq!(arch, "xtensa");
        assert_eq!(os, "freestanding");
        assert_eq!(cpu, "esp32s3");
    }

    #[test]
    fn test_map_target_thumb() {
        let (arch, os, _) = ZigGenerator::map_target(&TargetArch::NoneEabi);
        assert_eq!(arch, "thumb");
        assert_eq!(os, "freestanding");
    }

    #[test]
    fn test_map_target_x86_64() {
        let (arch, os, _) = ZigGenerator::map_target(&TargetArch::X86_64);
        assert_eq!(arch, "x86_64");
        assert_eq!(os, "linux");
    }

    #[test]
    fn test_is_cross_false_for_x86() {
        assert!(!ZigGenerator::is_cross(&TargetArch::X86_64));
        assert!(!ZigGenerator::is_cross(&TargetArch::X86));
    }

    #[test]
    fn test_is_cross_true_for_arm() {
        assert!(ZigGenerator::is_cross(&TargetArch::ARM32));
        assert!(ZigGenerator::is_cross(&TargetArch::Xtensa));
    }

    #[test]
    fn test_generate_does_not_panic() {
        let tmp = tempfile::tempdir().unwrap();
        let config = ProjectConfig {
            name: "test_zig".into(),
            root: tmp.path().to_path_buf(),
            ..Default::default()
        };
        let gen = ZigGenerator::new(&config).unwrap();
        let modules = vec![];
        let graph = DependencyGraph::new();
        let result = gen.generate(&modules, &graph, true, &[]);
        assert!(result.is_ok());
        assert!(tmp.path().join("build.zig").exists());
    }

    #[test]
    fn test_build_system_default_is_cmake() {
        assert_eq!(BuildSystem::default(), BuildSystem::CMake);
    }
}
